### ISSUE TITLE
wifi2 block should set LC_ALL for nmcli

### ISSUE THREAD

**Issue by nchachereau** [regolith-linux/regolith-i3xrocks-config#24]
If the user's language isn't English (in my case, French), the `wifi2` block / script does not work, because nmcli does not output "yes".

From [nmcli's man page](https://developer.gnome.org/NetworkManager/stable/nmcli.html):

> Be aware that nmcli is localized and that is why the output depends on your environment. This is important to realize especially when you parse the output.
> 
> Call nmcli as LC_ALL=C nmcli to be sure the locale is set to C while executing in a script.

**Comment by kgilmer** [comment]
Verified by setting Language to French in gnome-control-center, rebooting, and observing `non`/`oui` in nmcli output.  

Verified fix by prefixing command with `LC_ALL=C` and observing `yes`/`no`.

**Comment by kgilmer** [comment]
Thank you for the detailed issue report and suggestions to a fix @nchachereau .  The fix is building in `unstable` now and I will post to the mailing list when the fix is promoted to `release`.  If you'd like a Regolith laptop sticker, DM me a postal address on slack or kgilmer at gmail.com for mail.
