### ISSUE TITLE
Update broke my config

### ISSUE THREAD

**Issue by peturh** [regolith-linux/regolith-i3xrocks-config#48]
After updating I lost my config. I now only see workspaces and the little (i) in the corner.

I used the regolith iso image from just a short while ago. There came an update and I asked to keep my config. But that broke my desktop and now I cant see wifi status, volume etc.

I tried `sudo dpkg-reconfigure regolith-desktop` without success.

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```
```
Linux petur-t450 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by farsil** [comment]
Blocklets configuration has changed in 1.4, they need to be installed manually. Perhaps this giude addresses your issue?

https://regolith-linux.org/docs/howto/add-remove-blocklets/

**Comment by peturh** [comment]
> Blocklets configuration has changed in 1.4, they need to be installed manually. Perhaps this giude addresses your issue?
> 
> https://regolith-linux.org/docs/howto/add-remove-blocklets/

Thank you very much for pointing me into the right direction, but I do indeed have stuff in my /conf.d/ folder

```
ls /etc/regolith/i3xrocks/conf.d
01_setup  30_net-traffic  50_memory  80_rofication
```

But they're still not showing up, not after `regolith-look refresh` or `super+shift+r`

I still think my config file is somehow bad. The i3 config file looks nothing like it did before. I've modified `/etc/regolith/i3/config` in the past, but should I modify `/etc/regolith/i3xrocks/config` now?

**Comment by farsil** [comment]
You shouldn't have `/etc/regolith/i3xrocks/config` in the first place, because all configuration is done with the `conf.d` folder. Try removing it (make a backup first just in case!).

**Comment by kgilmer** [comment]
@peturh , it sounds like you've got an inconsistent installation of Regolith due to manual edits to files in `/etc/regolith` only being partially updated by the package manager.  I am not sure what the root cause of this issue is, but deal with it myself from time to time.  To resolve it, check here: https://regolith-linux.org/docs/getting-started/install/#edits-to-etcregolith-files

Also, to get back to the default set of config files once your packages are properly installed, see here: https://regolith-linux.org/docs/getting-started/install/#upgrading-with-customizations

**Comment by peturh** [comment]
That did the trick. 

Thank you. To be honest I had no idea the documentation was this extensive.
