### ISSUE TITLE
keyboard layout isn't working

### ISSUE THREAD

**Issue by mjgritli** [regolith-linux/regolith-i3xrocks-config#50]
Dear Regolith,

Its been wonderful seeing the modular approach you used for making Regolith-linux.

I've Installed Regolith:ppa about 4 days ago, everything is working fine, although I have 2 issue, 1 is related to i3xrocks, specifically, keyboard-layout indicator;
It is not working, its not switch layouts, I think the monitor isn't working,
when I made a similar script, but set interval=1, it works, but nor monitoring gnome switching.

Is there anything I can do to help.

**Comment by kgilmer** [comment]
Hi @mjgritli , there are some fixes coming that may address your problems.  A update to `keyboard-layout` by @kirushik was published to the `unstable` PPA yesterday.  If testing goes well this will get to the `release` PPA this weekend, and then you'll be able to pick up the update.

Regarding your second update, can you provide more details?  This is a display issue or a i3rocks issue?

**Comment by mjgritli** [comment]
Hi @kgilmer 
Thanks for your reply, Yh, the second issue is with "time", upon clicking, it opens system settings, no the gnome calendar app, I think it would be more appropriate to open calendar, as anyone can access system settings.
Thanks again

**Comment by kgilmer** [comment]
Ah, ok I understand.  Well, gnome-calendar isn't a current dependency, so I would have to add that.  I prefer to keep the list of required packages as small as possible so users have more freedom to choose their tools.  But, there is a similar request to allow users to specify the programs that are launched when you click on various items on the bar: https://github.com/regolith-linux/regolith-desktop/issues/352

Once this is added you'll be able to specify in Xresources that you want to launch a calendar instead of the time settings.

**Comment by mjgritli** [comment]
Hi @kgilmer 
I can confirm, the issue is resolved with the last update.
Thank you
